extends Node

# --- MAP GENERATION EXPORTS ---
# --- MAP GENERATION EXPORTS ---
@export var tree_scenes: Array[PackedScene]
@export var rock_scenes: Array[PackedScene]
@export var building_scenes: Array[PackedScene]
@export var statue_scene: PackedScene

@onready var grid_background = $GridBackground
@onready var dirt_layer = $DirtLayer
@onready var decor_layer = $DecorationsLayer

var map_width = 150
var map_height = 150
var world_size = 2400 # map_width * 16 pixels
var num_blockers = 150

# --- LEVEL UP AUDIO ---
var level_up_sounds = [
	preload("res://assets/Ninja Adventure - Asset Pack/Audio/Jingles/LevelUp1.wav"), 
	preload("res://assets/Ninja Adventure - Asset Pack/Audio/Jingles/LevelUp2.wav"),
	preload("res://assets/Ninja Adventure - Asset Pack/Audio/Jingles/LevelUp3.wav")
]

# --- EXISTING NODES --- 
@onready var mob_spawner = $MobSpawner
@onready var reinforcement_screen = $CanvasLayer/Control
@onready var title_screen = $CanvasLayer/TitleScreen
@onready var game_over_screen = $CanvasLayer/GameOverScreen
@onready var ingame_UI = $CanvasLayer/UI

var levels_at_high_hp: int = 0
var current_director_intensity: float = 1.0 # 1.0 is Normal, <1.0 is Easy, >1.0 is Hard

# Talo
var _game_start_time: float = 0.0
var heartbeat_timer: float = 0.0
const HEARTBEAT_INTERVAL: float = 15.0 # Save to Talo every 60 seconds


var cluster_bonus: int = 0
var previous_level_hp: int = -1

var is_leveling_up: bool = false

# Called when the node enters the scene tree for the first time.
func _ready() -> void:	
	ingame_UI.hide()
	title_screen.hide()
	# ----------------------------------------
	
	reinforcement_screen.wave_started.connect(_on_wave_started)
	mob_spawner.set_wave_config([
		{"type": "bear", "weight": 0.2},
		{"type": "ghost", "weight": 0.2},
		{"type": "mushroom", "weight": 0.6},
	])
	title_screen.start_game.connect(_on_start_game)
	game_over_screen.restart_game.connect(_on_restart_game)
  
	generate_ground()
	spawn_blockers()
	setup_boundaries()
	
	# Now the game waits for the server, but the screen is already hidden!
	# THE CROSSROADS
	if GameData.is_quick_restart:
		_on_start_game() 
	else:
		title_screen_ready()
		await _init_player()
		GameData.sync_from_talo()
		
	# connect dragon signal for changing BGM
	mob_spawner.dragon_spawned.connect(_on_spawner_boss_dragon_spawned_signal)
	mob_spawner.dragon_died.connect(_on_spawner_boss_dragon_died_signal)
	GameData.leveled_up.connect(_on_player_level_up)
	
	
func _init_player() -> void:
	var final_id = ""
	if OS.get_name() == "Web":
		print("[Talo Debug] Platform detected: Web")
		final_id = JavaScriptBridge.eval("localStorage.getItem('talo_player_id') || ''")
		
		if final_id == "":
			final_id = "guest_" + str(randi()) + str(Time.get_ticks_msec())
			JavaScriptBridge.eval("localStorage.setItem('talo_player_id', '%s')" % final_id)
	else:
		final_id = Talo.players.generate_identifier()
	
	# Attempt identification
	await Talo.players.identify("guest", final_id)


	# --- NEW: START THE SESSION CLOCK ---
	GameData.session_start_time = Time.get_unix_time_from_system()
	
func title_screen_ready():
	Input.mouse_mode = Input.MOUSE_MODE_VISIBLE
	get_tree().paused = true
	game_over_screen.hide()
	ingame_UI.hide()
	title_screen.show()
	
func _on_start_game():
	# Only confine the mouse if we are NOT playing on the web
	if not OS.has_feature("web"):
		Input.mouse_mode = Input.MOUSE_MODE_CONFINED
	
		
	title_screen.hide()
	game_over_screen.hide()
	ingame_UI.show()
	get_tree().paused = false
	new_game()
	

func _input(event: InputEvent) -> void:
	# 1. Count Keyboard Presses (WASD, Arrows, etc.)
	# The "not event.is_echo()" check is crucial! It ensures we only count 
	# the initial press, not the spam generated by holding the key down.
	if event is InputEventKey and event.is_pressed() and not event.is_echo():
		GameData.total_actions += 1
		
	# 2. Count Mouse Clicks (Shop buys, rerolls, UI interactions)
	elif event is InputEventMouseButton and event.is_pressed():
		GameData.total_actions += 1


func game_over():
	var duration = int(Time.get_unix_time_from_system() - _game_start_time)
	var total_session_duration = int(Time.get_unix_time_from_system() - GameData.session_start_time)
	var final_killer = GameData.killer_name
	
	
	
	var elapsed_minutes = float(duration) / 60.0
	var final_apm = 0
	if elapsed_minutes > 0:
		final_apm = int(GameData.total_actions / elapsed_minutes)
	
	GameData.meta_crystals += GameData.total_exp_collected
	Talo.current_player.set_prop("total_meta_crystals", str(GameData.meta_crystals))
	
	Talo.events.track("game_over", {
		"duration_seconds": str(duration),
		"total_gold_collected": str(GameData.total_gold_collected),
		"gold_spent_in_game": str(GameData.gold_spent_in_game),
		"level_reached": str(GameData.level),
		"time_taken_per_level": str(GameData.time_taken_per_level),
		"killed_by": final_killer,
		"actions_per_minute": str(final_apm),
		"meta_crystals_earned": str(GameData.total_exp_collected)
	})
	# --- NEW: UPDATE PLAYER'S TOTAL TIME PROP ---
	if Talo.current_alias:
		# This updates a permanent property on the player in your Talo dashboard!
		Talo.current_player.set_prop("total_session_seconds", str(total_session_duration))
		Talo.current_player.set_prop("highest_level_reached", str(GameData.highest_level_reached))
	
	Talo.events.flush()
	print("Talo flush done")
	Input.mouse_mode = Input.MOUSE_MODE_VISIBLE
	$MobTimer.stop()
	game_over_screen_ready()

func game_over_screen_ready():
	get_tree().paused = true
	game_over_screen.final_gold_level(GameData.gold, GameData.level)
	game_over_screen.show()

func _on_restart_game():
	Talo.events.track("restart_game", {
		"level_reached": str(GameData.level),
		"gold_banked": str(GameData.gold)
	})
	await Talo.events.flush()
	GameData.reset_gamedata()
	GameData.is_quick_restart = true
	get_tree().paused = false
	get_tree().reload_current_scene()

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	# Update UI from GameData (Source of Truth)
	ingame_UI.update_gold(GameData.gold)
	ingame_UI.update_exp(GameData.current_exp, GameData.exp_to_level_up)
	ingame_UI.update_level(GameData.level)
	
	if has_node("Commander"):
		ingame_UI.update_hp($Commander.hp, $Commander.max_hp)
		
	# --- NEW: THE COMBINED TALO HEARTBEAT ---
	# Only run the heartbeat if the player is logged in
	if Talo.current_player:
		heartbeat_timer += delta
		
		# Every 60 seconds...
		if heartbeat_timer >= HEARTBEAT_INTERVAL:
			heartbeat_timer = 0.0 # Reset the clock
			
			if GameData.session_start_time > 0:
				# 1. Update the overall session property
				var total_session_duration = int(Time.get_unix_time_from_system() - GameData.session_start_time)
				Talo.current_player.set_prop("total_session_seconds", str(total_session_duration))
				
				# 2. THE FIX: Calculate APM using the current run's time!
				var current_run_duration = int(Time.get_unix_time_from_system() - _game_start_time)
				var elapsed_minutes = float(current_run_duration) / 60.0
				
				# Prevent dividing by zero in the first few seconds
				if elapsed_minutes > 0.05:
					var current_apm = int(GameData.total_actions / elapsed_minutes)
					Talo.current_player.set_prop("average_apm", str(current_apm))
			
			# 3. Silently backup their absolute highest level reached!
			Talo.current_player.set_prop("highest_level_reached", str(GameData.highest_level_reached))
			
			# --- NEW: Track who is currently hurting them! ---
			# We use the killer_name variable, but label it "last_damaged_by" in Talo
			Talo.current_player.set_prop("last_damaged_by", GameData.killer_name)
			# -------------------------------------------------
			
			# 4. Save State at Exit
			# Always save their current gold, even if they are in a menu!
			Talo.current_player.set_prop("last_known_gold", str(GameData.gold))
			
			# Only try to save their HP if they are actively alive in the level
			if has_node("Commander"):
				var hp_percent = float($Commander.hp) / float($Commander.max_hp)
				Talo.current_player.set_prop("last_known_hp_percent", str(hp_percent))
	# ----------------------------------------

func new_game():
	_game_start_time = Time.get_unix_time_from_system()
	$Commander.start($StartPosition.position)
	$StartTimer.start()

func _on_mob_timer_timeout() -> void:
	# random spown position
	var mob_spawn_location = get_mob_spawn_position()
	
	# use mobspawner to generate a mob
	var mob = mob_spawner.spawn_random_mob(
		mob_spawn_location + Vector2(100, 0),
		$Commander
	)
	
	# add to sceneww
	add_child(mob)

func _on_ghost_timer_timeout() -> void:
	var mob_spawn_location = get_mob_spawn_position()
	mob_spawner.spawn_cluster("ghost", mob_spawn_location, $Commander, randi_range(1, 5) + cluster_bonus)

func _on_bear_timer_timeout() -> void:
	var mob_spawn_location = get_mob_spawn_position()
	# Your old bear function didn't pass a count, which defaults to 1. 
	# Let's pass the count so the bears scale up too!
	mob_spawner.spawn_cluster("bear", mob_spawn_location, $Commander, 1 + cluster_bonus)

func _on_mushroom_timer_timeout() -> void:
	var mob_spawn_location = get_mob_spawn_position()
	mob_spawner.spawn_cluster("mushroom", mob_spawn_location, $Commander, randi_range(1, 2) + cluster_bonus)

# Add the boolean parameter here, defaulting to false
func get_mob_spawn_position(is_boss: bool = false):
	var mob_spawn_location = $Commander/MobPath/MobSpawnLocation
	mob_spawn_location.progress_ratio = randf()
	
	var raw_pos = mob_spawn_location.global_position
	
	# THE FIX: If it's a boss, give them the raw edge-of-screen position!
	if is_boss:
		return raw_pos
		
	# Otherwise, it's a normal mob, so shrink the distance
	var commander_pos = $Commander.global_position
	return raw_pos.lerp(commander_pos, 0.4)

func _on_start_timer_timeout() -> void:
	$MobTimer.start()
	
	$GhostTimer.start()
	$BearTimer.start()
	$MushroomTimer.start()
	$FlamethrowerTimer.start()
	
# --- SHOP LOGIC ---
func _on_wave_started():
	# Unpause the game world when "Deploy" is clicked
	get_tree().paused = false

# (Optional: Just for testing right now, let's open it when you press 'Tab')
func _unhandled_input(event):
	if event.is_action_pressed("ui_focus_next"): # Usually the 'Tab' key
		open_shop()
	# --- DEBUG: PRESS 'F' TO SPAWN BOSS ---
	if OS.is_debug_build() and event is InputEventKey:
		if event.pressed and event.keycode == KEY_F:
			print("[DEBUG] Forced Boss Spawn!")
			var spawn_pos = get_mob_spawn_position()
			# We force the call to spawn_mob directly from the dictionary
			var boss = mob_spawner.spawn_mob("boss", spawn_pos, $Commander)
			if boss:
				add_child(boss)
	
func open_shop():
	get_tree().paused = true
	reinforcement_screen.visible = true
	reinforcement_screen.on_shop_opened()


# ==========================================
# --- MAP GENERATION LOGIC ---
# ==========================================
func generate_ground():
	var noise = FastNoiseLite.new()
	noise.seed = randi()
	
	# 1. Use Simplex Smooth instead of Perlin for rounder, "blobby" shapes
	noise.noise_type = FastNoiseLite.TYPE_SIMPLEX_SMOOTH
	
	# 2. Turn OFF the rough edges completely to stop the "hairy" spikes
	noise.fractal_type = FastNoiseLite.FRACTAL_NONE
	
	# 3. Zoom in just a little bit more to make the clearings larger
	noise.frequency = 0.015 

	var dirt_cells: Array[Vector2i] = []

	for x in range(-map_width / 2, map_width / 2):
		for y in range(-map_height / 2, map_height / 2):
			var cell_coords = Vector2i(x, y)
			var noise_val = noise.get_noise_2d(x, y)
			
			# Grass base
			grid_background.set_cell(cell_coords, 0, Vector2i(1, 7)) 
			
			# 4. Higher threshold + Simplex = natural, isolated dirt clearings
			if noise_val > 0.2:
				dirt_cells.append(cell_coords)
			else:
				# 3. Decoration Layer (Only on Grass)
				var rand_decor = randf()
				if rand_decor > 0.95: 
					var pebble_coords = Vector2i(15, 18) 
					if randf() > 0.5:
						pebble_coords = Vector2i(16, 18) 
					decor_layer.set_cell(cell_coords, 2, pebble_coords)

	# Tell Godot to connect the dirt on the Dirt layer
	dirt_layer.set_cells_terrain_connect(dirt_cells, 0, 0)

func spawn_blockers():
	# Instead of just storing positions, we store a Dictionary with all info!
	var placed_objects: Array[Dictionary] = []
	
	# --- DISTANCE RULES ---
	var min_distance = 70.0 # Absolute minimum distance to prevent physical overlap
	var same_building_min_distance = 250.0 # How far away identical buildings must be
	var safe_spawn_radius = 80
	var spawn_point = $StartPosition.position
	
	# --- CLUSTER MAP ---
	var cluster_noise = FastNoiseLite.new()
	cluster_noise.seed = randi()
	cluster_noise.frequency = 0.025 # Creates distinct "islands" of obstacles
	
	# Dropped from 800 to 400 to heavily reduce overall map density
	var total_to_spawn = 300
	
	for i in range(total_to_spawn):
		var spawn_pos = Vector2.ZERO
		var is_valid_position = false
		var attempts = 0
		
		# Variables to hold our choice before we place it
		var scene_to_instantiate = null
		var is_building = false
		var resource_path = ""
		
		# Try up to 30 times to find a valid spot
		while not is_valid_position and attempts < 30:
			var margin = 100
			spawn_pos = Vector2(
				randf_range(-world_size / 2 + margin, world_size / 2 - margin),
				randf_range(-world_size / 2 + margin, world_size / 2 - margin)
			)
			
			# 1. Safe Zone Check
			if spawn_pos.distance_to(spawn_point) < safe_spawn_radius:
				attempts += 1
				continue
				
			# 2. CLUSTER CHECK (This forces everything to group together!)
			var n_val = cluster_noise.get_noise_2d(spawn_pos.x, spawn_pos.y)
			if n_val < 0.15: 
				# If noise is low, it's a Meadow. Force it to be empty!
				attempts += 1
				continue
				
			# 3. PRE-SELECT THE OBJECT
			# Since we are in a valid cluster, pick what we want to place here
			var rand = randf()
			if rand < 0.15 and building_scenes.size() > 0:       # 15% Buildings
				scene_to_instantiate = building_scenes.pick_random()
				is_building = true
			elif rand < 0.20 and statue_scene != null:           # 5% Statues
				scene_to_instantiate = statue_scene
			elif rand < 0.85 and tree_scenes.size() > 0:         # 65% Trees
				scene_to_instantiate = tree_scenes.pick_random()
			elif rock_scenes.size() > 0:                         # 15% Rocks
				scene_to_instantiate = rock_scenes.pick_random()
			else:
				attempts += 1
				continue
				
			# Grab the unique file path so we can identify exact duplicates
			resource_path = scene_to_instantiate.resource_path
			is_valid_position = true
			
			# 4. PROXIMITY & DUPLICATE CHECKS
			for placed in placed_objects:
				var dist = spawn_pos.distance_to(placed["pos"])
				
				# Rule A: Prevent clipping for everything
				if dist < min_distance:
					is_valid_position = false
					break
					
				# Rule B: Allow different buildings to be close, but ban identical ones!
				if is_building and placed["is_building"]:
					if dist < same_building_min_distance and resource_path == placed["path"]:
						is_valid_position = false
						break 
			
			attempts += 1
			
		# --- SPAWN LOGIC ---
		if is_valid_position and scene_to_instantiate != null:
			var blocker_instance = scene_to_instantiate.instantiate()
			
			# Save all the data into our dictionary list
			placed_objects.append({
				"pos": spawn_pos,
				"path": resource_path,
				"is_building": is_building
			})
			
			blocker_instance.position = spawn_pos
			
			# Add subtle random scaling to organic things
			if not is_building and not blocker_instance.name.contains("Statue"):
				var random_scale = randf_range(0.85, 1.15)
				blocker_instance.scale = Vector2(random_scale, random_scale)
				
			add_child(blocker_instance)
			

func setup_boundaries():
	var boundary_body = StaticBody2D.new()
	boundary_body.name = "MapBoundaries"
	
	boundary_body.collision_layer = 1 << (7 - 1)
	
	# We use collision layer 1 so the Commander and Mobs collide with it
	add_child(boundary_body)
	
	var thickness = 200
	var half_size = world_size / 2
	
	# Define the 4 walls (Top, Bottom, Left, Right)
	var walls = [
		{"pos": Vector2(0, -half_size - thickness/2), "size": Vector2(world_size + thickness*2, thickness)}, # Top
		{"pos": Vector2(0, half_size + thickness/2), "size": Vector2(world_size + thickness*2, thickness)},  # Bottom
		{"pos": Vector2(-half_size - thickness/2, 0), "size": Vector2(thickness, world_size)}, # Left
		{"pos": Vector2(half_size + thickness/2, 0), "size": Vector2(thickness, world_size)}   # Right
	]
	
	# Build the walls
	for wall in walls:
		var collision = CollisionShape2D.new()
		var rect = RectangleShape2D.new()
		rect.size = wall["size"]
		collision.shape = rect
		collision.position = wall["pos"]
		boundary_body.add_child(collision)

# 3. Add this brand new function anywhere in main.gd!
func increase_difficulty(current_level: int):
	var current_hp = $Commander.hp
	var max_hp = $Commander.max_hp
	var current_hp_percent = float(current_hp) / float(max_hp)
	
	# Initialize previous_hp on the very first level up
	if previous_level_hp == -1:
		previous_level_hp = current_hp
		
	# Calculate the Momentum (Did they lose or gain health this level?)
	var hp_delta_percent = float(current_hp - previous_level_hp) / float(max_hp)
	
	# --- 1. EVALUATE PLAYER PERFORMANCE (MOMENTUM & TIERS) ---
	
	# Calculate APM for AFK detection
	var run_duration = max(0.1, float(Time.get_unix_time_from_system() - _game_start_time) / 60.0)
	var current_apm = int(GameData.total_actions / run_duration)

	# TIER 1: THE AFK PUNISHER
	if current_hp_percent >= 0.75 and current_apm < 15:
		current_director_intensity += 0.8
		cluster_bonus += 2
		
		# Get the base spawn location
		var base_spawn_pos = get_mob_spawn_position()
		
		# 1. Spawn the Samurai Boss with a slight offset
		var samurai_offset = Vector2(randf_range(-150, 150), randf_range(-150, 150))
		var samurai_boss = mob_spawner.spawn_mob("boss", base_spawn_pos + samurai_offset, $Commander)
		if samurai_boss:
			call_deferred("add_child", samurai_boss)
			
		# 2. Spawn the Bamboo Boss with a different offset
		var bamboo_offset = Vector2(randf_range(-150, 150), randf_range(-150, 150))
		var bamboo_boss = mob_spawner.spawn_mob("boss_bamboo", base_spawn_pos + bamboo_offset, $Commander)
		if bamboo_boss:
			call_deferred("add_child", bamboo_boss)

		print("[Director] ENRAGED! Player is AFK. Spawning Samurai AND Bamboo Bosses!")

	# TIER 2: THE "GLASS CANNON" (Low HP, taking zero damage, hoarding gold)
	elif current_hp_percent < 0.35 and hp_delta_percent >= 0.0 and GameData.gold >= 15:
		current_director_intensity += 0.1
		print("[Director] GLASS CANNON DETECTED! Stable at low HP. Raising intensity to ", current_director_intensity)

	# TIER 3: ACTUAL CRITICAL (Low HP AND actively took damage this level)
	elif current_hp_percent < 0.25 and hp_delta_percent < 0.0:
		current_director_intensity = max(0.4, current_director_intensity - 0.4) 
		
		# --- ACTIVE RELIEF (Panic Mode) ---
		# 1. Instantly shrink swarm sizes
		cluster_bonus = max(0, cluster_bonus - 2) 
		
		# 2. Push spawn timers backwards (Slows down spawning by 50%)
		$MobTimer.wait_time *= 1.5 
		$GhostTimer.wait_time *= 1.5
		$BearTimer.wait_time *= 1.5
		$MushroomTimer.wait_time *= 1.5
		
		# 3. Instantly nerf incoming mob health by 20%
		mob_spawner.health_multiplier = max(1.0, mob_spawner.health_multiplier * 0.8) 
		# ----------------------------------
		
		print("[Director] CRITICAL! Active relief triggered! Timers slowed 50%, health nerfed.")

	# TIER 4: MASSIVE BLEED (Lost a huge chunk of HP this level)
	elif hp_delta_percent <= -0.30:
		current_director_intensity = max(0.6, current_director_intensity - 0.25)
		
		# --- ACTIVE RELIEF (Recovery Mode) ---
		# 1. Strip away 1 layer of swarm scaling
		cluster_bonus = max(0, cluster_bonus - 1)
		
		# 2. Push spawn timers backwards (Slows down spawning by 25%)
		$MobTimer.wait_time *= 1.25
		$GhostTimer.wait_time *= 1.25
		$BearTimer.wait_time *= 1.25
		$MushroomTimer.wait_time *= 1.25
		
		# 3. Instantly nerf incoming mob health by 10%
		mob_spawner.health_multiplier = max(1.0, mob_spawner.health_multiplier * 0.9)
		# ----------------------------------

		print("[Director] BLEEDING! Active relief triggered! Timers slowed 25%.")

	# TIER 5: DOMINATING (High HP, took zero damage)
	elif current_hp_percent > 0.85 and hp_delta_percent >= 0.0:
		current_director_intensity += 0.2 
		print("[Director] DOMINATING! Raising intensity to ", current_director_intensity)

	# TIER 6: UNTOUCHABLE (Catch-all for ANY flawless wave not caught by T2 or T5)
	elif hp_delta_percent >= 0.0:
		current_director_intensity += 0.15
		print("[Director] UNTOUCHABLE! Flawless wave. Raising intensity to ", current_director_intensity)

	# TIER 7: SLOW BLEED / STRUGGLING (HP is below 50% and they took chip damage)
	elif current_hp_percent < 0.50 and hp_delta_percent < 0.0:
		current_director_intensity = max(0.75, current_director_intensity - 0.1)
		print("[Director] STRUGGLING! Slow bleed detected. Easing intensity to ", current_director_intensity)

	# TIER 8: COASTING (Mid-to-High HP, taking normal chip damage)
	else:
		current_director_intensity = lerp(current_director_intensity, 1.0, 0.25)

	# Update the tracker for the NEXT level
	previous_level_hp = current_hp

	# --- 2. EVALUATE ECONOMY ---
	if current_level >= 5 and GameData.gold < 5:
		GameData.gold_drop_chance = min(1.0, GameData.gold_drop_chance + 0.4)
	elif GameData.gold >= 20:
		GameData.gold_drop_chance = max(0.25, 1.0 - (current_level * 0.03))

	# --- 3. APPLY THE SCALING ---
	if current_level % 2 != 0:
		var spawn_reduction = 1.0 - (0.05 * current_director_intensity) 
		$MobTimer.wait_time = max(0.6, $MobTimer.wait_time * spawn_reduction)
		$GhostTimer.wait_time = max(0.6, $GhostTimer.wait_time * spawn_reduction)
		$BearTimer.wait_time = max(0.7, $BearTimer.wait_time * spawn_reduction)
		$MushroomTimer.wait_time = max(0.8, $MushroomTimer.wait_time * spawn_reduction)

	if current_level % 2 == 0:
		var health_growth = 0.4 * current_director_intensity
		mob_spawner.health_multiplier = 1.0 + (sqrt(current_level) * health_growth)
		
		if current_level % 4 == 0:
			if current_director_intensity >= 1.15: # Raised threshold so swarms only grow when actually dominating
				cluster_bonus += 1
			elif current_director_intensity <= 0.6:
				cluster_bonus = max(0, cluster_bonus - 1) 
			
	print("[Level ", current_level, " Setup] Intensity: ", current_director_intensity, " | HP Multiplier: ", snapped(mob_spawner.health_multiplier, 0.1))

func _fade_switch_music(from_node: Node, to_node: Node, duration: float = 2.0):
	if from_node == to_node: return
	
	to_node.volume_db = -80.0
	if not to_node.playing:
		to_node.play()
	
	var tween = create_tween().set_parallel(true)
	
	tween.tween_property(from_node, "volume_db", -80.0, duration).set_trans(Tween.TRANS_SINE)
	
	tween.tween_property(to_node, "volume_db", 0.0, duration).set_trans(Tween.TRANS_SINE)
	
	tween.chain().tween_callback(func():
		from_node.stop()
	)
	
func _on_spawner_boss_dragon_spawned_signal():
	_fade_switch_music($"BGM-main", $"BGM-dragon", 2.0)
	
func _on_spawner_boss_dragon_died_signal():
	await get_tree().process_frame
	
	var alive_dragons = 0
	for dragon in get_tree().get_nodes_in_group("dragon_bosses"):
		if not dragon.is_queued_for_deletion(): 
			alive_dragons += 1
	# don't ask me why it is "1", it is how it is
	if alive_dragons == 1:
		_fade_switch_music($"BGM-dragon", $"BGM-main", 3.0)

func _on_player_level_up(new_level: int):
	# 1. TRIGGER PROGRESSION IMMEDIATELY 
	
	# THE FIX: Pass 'true' so the game knows to spawn them far away!
	var spawn_pos = get_mob_spawn_position(true) 
	
	mob_spawner.try_spawn_boss(new_level, spawn_pos, $Commander)
	increase_difficulty(new_level)
	
	# 2. TRIGGER THE VISUALS 
	if not is_leveling_up:
		trigger_level_up_juice()

func trigger_level_up_juice():
	is_leveling_up = true
	var juice_duration = 2 
	
	# --- NEW: PLAY RANDOM AUDIO ---
	if has_node("LevelUpAudio"):
		$LevelUpAudio.stream = level_up_sounds.pick_random()
		$LevelUpAudio.play()
	# ------------------------------

	# 1. TRIGGER THE BURST ANIMATION (Normal Speed)
	if has_node("Commander/LevelUpBurst"):
		$Commander/LevelUpBurst.show()
		$Commander/LevelUpBurst/AnimationPlayer.speed_scale = 1.0 
		$Commander/LevelUpBurst/AnimationPlayer.play("burst")
	
	# 2. CREATE THE SCREEN FLASH
	var flash = ColorRect.new()
	flash.color = Color(1, 1, 1, 1) # Pure white
	flash.set_anchors_preset(Control.PRESET_FULL_RECT)
	add_child(flash) 
	
	# Tween the flash to fade out over the duration
	var tween = create_tween()
	tween.tween_property(flash, "color:a", 0.0, juice_duration)
	tween.tween_callback(flash.queue_free) 
	
	# 4. WAIT FOR THE JUICE TO FINISH
	await get_tree().create_timer(juice_duration).timeout
	
	# 5. CLEANUP AND OPEN SHOP
	if has_node("Commander/LevelUpBurst"):
		$Commander/LevelUpBurst.hide()
	
	is_leveling_up = false
	
	print("Level Up Juice Finished! Opening Shop...")
	open_shop()

func _on_flamethrower_timer_timeout() -> void:
	var mob_spawn_location = get_mob_spawn_position()
	mob_spawner.spawn_cluster("flamethrower", mob_spawn_location, $Commander, 1 + cluster_bonus)
